import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { useBreakpoint } from "@/hooks/useBreakpoint";
import { PageTitle } from "@/components/shared/PageTitle";
import { motion, AnimatePresence } from "framer-motion";

interface BMRResult {
  bmr: number;
  tdee: number;
  target: number;
  protein: number;
  recommendation: string;
}

const ACTIVITY_LEVELS = [
  { value: 1.2, label: "Sedentary", sub: "Little or no exercise" },
  { value: 1.375, label: "Light", sub: "1–3 days/week" },
  { value: 1.55, label: "Moderate", sub: "3–5 days/week" },
  { value: 1.725, label: "Very Active", sub: "6–7 days/week" },
  { value: 1.9, label: "Athlete", sub: "Intense daily training" },
];

const GOALS = [
  { value: "lose", label: "Lose Fat", icon: "🔥", deficit: -0.2 },
  { value: "maintain", label: "Maintain", icon: "⚖️", deficit: 0 },
  { value: "gain", label: "Gain Muscle", icon: "💪", deficit: +0.1 },
];

function round(n: number) {
  return Math.round(n);
}

function calcBMR(gender: string, weight: number, height: number, age: number) {
  if (gender === "male") return 10 * weight + 6.25 * height - 5 * age + 5;
  return 10 * weight + 6.25 * height - 5 * age - 161;
}

function getRecommendation(
  goal: string,
  tdee: number,
  target: number,
  weight: number,
) {
  const diff = Math.abs(round(tdee - target));
  if (goal === "lose")
    return `You're in a ${diff} kcal deficit. Prioritise protein (${round(weight * 2)}g/day) and strength training to preserve muscle while losing fat. Aim for 0.5–1kg loss per week.`;
  if (goal === "gain")
    return `You're in a ${diff} kcal surplus. Focus on progressive overload training and protein (${round(weight * 2)}g/day). Aim for 0.25–0.5kg muscle gain per week.`;
  return `You're eating at maintenance. Track weekly weight — if it drifts, adjust by 100–200 kcal. Keep protein at ${round(weight * 1.8)}g/day and training consistent.`;
}

export function BMR() {
  const { user } = useAuth();
  const { isMobile } = useBreakpoint();

  const [gender, setGender] = useState("male");
  const [weight, setWeight] = useState("");
  const [height, setHeight] = useState("");
  const [age, setAge] = useState("");
  const [activity, setActivity] = useState(1.55);
  const [goal, setGoal] = useState("maintain");
  const [result, setResult] = useState<BMRResult | null>(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");

  const calculate = () => {
    const w = parseFloat(weight);
    const h = parseFloat(height);
    const a = parseInt(age);
    if (!w || !h || !a || w <= 0 || h <= 0 || a <= 0) {
      setError("Please fill in all fields with valid numbers.");
      return;
    }
    setError("");
    const bmr = calcBMR(gender, w, h, a);
    const tdee = bmr * activity;
    const goalObj = GOALS.find((g) => g.value === goal)!;
    const target = Math.max(tdee + tdee * goalObj.deficit, 1200);
    const protein = round(w * 2);
    setResult({
      bmr: round(bmr),
      tdee: round(tdee),
      target: round(target),
      protein,
      recommendation: getRecommendation(goal, tdee, target, w),
    });
  };

  const reset = () => {
    setResult(null);
    setWeight("");
    setHeight("");
    setAge("");
    setError("");
  };

  const copyToAI = async () => {
    if (!result) return;
    const actLabel = ACTIVITY_LEVELS.find((a) => a.value === activity)?.label;
    const goalLabel = GOALS.find((g) => g.value === goal)?.label;
    const text = `📊 BMR CALCULATION — MK2 Rivers Fitness
━━━━━━━━━━━━━━━━━━━━━━
👤 Gender: ${gender === "male" ? "Male" : "Female"}
⚖️  Weight: ${weight} kg
📏 Height: ${height} cm
🎂 Age: ${age} years
🏃 Activity: ${actLabel}
🎯 Goal: ${goalLabel}

📈 YOUR NUMBERS:
- BMR (base metabolic rate): ${result.bmr} kcal/day
- TDEE (maintenance): ${result.tdee} kcal/day
- Daily Target: ${result.target} kcal/day
- Protein Target: ${result.protein}g/day

💡 RECOMMENDATION:
${result.recommendation}
━━━━━━━━━━━━━━━━━━━━━━
✅ Generated by MK2 Rivers BMR Calculator`;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      setCopied(false);
    }
  };

  const inp =
    "w-full bg-secondary border border-border rounded-lg px-4 py-3 text-foreground text-sm outline-none font-body focus:border-primary/50 transition-colors";
  const lbl =
    "text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground block mb-1.5";
  const goalColor =
    goal === "lose"
      ? "hsl(142 72% 37%)"
      : goal === "gain"
        ? "hsl(263 85% 58%)"
        : "hsl(38 92% 44%)";
  const goalIcon = GOALS.find((g) => g.value === goal)?.icon || "🎯";
  const goalLabel = GOALS.find((g) => g.value === goal)?.label || "";

  return (
    <div
      className={`max-w-[760px] mx-auto ${isMobile ? "px-3.5 py-5" : "px-6 py-10"}`}
    >
      <PageTitle sub="Calculate your daily calorie needs — copy results to the AI Nutrition Coach">
        BMR <span className="text-primary">Calculator</span>
      </PageTitle>

      <div
        className={`grid gap-4 ${isMobile ? "grid-cols-1" : "grid-cols-2"} mb-5`}
      >
        {/* Gender */}
        <div className="mk2-card col-span-full">
          <label className={lbl}>Gender</label>
          <div className="flex gap-2">
            {[
              ["male", "♂️ Male"],
              ["female", "♀️ Female"],
            ].map(([val, lab]) => (
              <button
                key={val}
                onClick={() => setGender(val)}
                className="flex-1 py-3 rounded-lg font-body font-bold text-sm cursor-pointer transition-all duration-150 border"
                style={{
                  background:
                    gender === val
                      ? "hsl(20 100% 50%)"
                      : "hsl(var(--secondary))",
                  color:
                    gender === val ? "#000" : "hsl(var(--muted-foreground))",
                  borderColor:
                    gender === val ? "hsl(20 100% 50%)" : "hsl(var(--border))",
                }}
              >
                {lab}
              </button>
            ))}
          </div>
        </div>

        {/* Weight */}
        <div className="mk2-card">
          <label className={lbl}>Weight (kg)</label>
          <input
            className={inp}
            type="number"
            placeholder="e.g. 78"
            value={weight}
            onChange={(e) => setWeight(e.target.value)}
          />
        </div>

        {/* Height */}
        <div className="mk2-card">
          <label className={lbl}>Height (cm)</label>
          <input
            className={inp}
            type="number"
            placeholder="e.g. 175"
            value={height}
            onChange={(e) => setHeight(e.target.value)}
          />
        </div>

        {/* Age */}
        <div className="mk2-card">
          <label className={lbl}>Age (years)</label>
          <input
            className={inp}
            type="number"
            placeholder="e.g. 28"
            value={age}
            onChange={(e) => setAge(e.target.value)}
          />
        </div>

        {/* Activity */}
        <div className="mk2-card">
          <label className={lbl}>Activity Level</label>
          <select
            className={inp}
            value={activity}
            onChange={(e) => setActivity(parseFloat(e.target.value))}
          >
            {ACTIVITY_LEVELS.map((a) => (
              <option
                key={a.value}
                value={a.value}
                style={{ background: "hsl(var(--secondary))" }}
              >
                {a.label} — {a.sub}
              </option>
            ))}
          </select>
        </div>

        {/* Goal */}
        <div className="mk2-card col-span-full">
          <label className={lbl}>Your Goal</label>
          <div className="grid grid-cols-3 gap-2">
            {GOALS.map((g) => (
              <button
                key={g.value}
                onClick={() => setGoal(g.value)}
                className="py-3 px-2 rounded-lg border font-body font-bold text-xs cursor-pointer transition-all duration-150 flex flex-col items-center gap-1"
                style={{
                  background:
                    goal === g.value
                      ? "hsl(20 100% 50%)"
                      : "hsl(var(--secondary))",
                  color:
                    goal === g.value ? "#000" : "hsl(var(--muted-foreground))",
                  borderColor:
                    goal === g.value
                      ? "hsl(20 100% 50%)"
                      : "hsl(var(--border))",
                }}
              >
                <span className="text-xl">{g.icon}</span>
                <span>{g.label}</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {error && (
        <div className="mb-4 px-4 py-3 rounded-lg text-sm text-red-400 bg-red-400/10 border border-red-400/20">
          {error}
        </div>
      )}

      <div className="flex gap-3 mb-6">
        <button
          onClick={calculate}
          className="flex-1 py-3.5 rounded-lg font-body font-bold text-sm uppercase tracking-[0.08em] border-none cursor-pointer transition-all duration-200"
          style={{
            background: "hsl(20 100% 50%)",
            color: "#000",
            boxShadow: "0 4px 20px hsl(20 100% 50% / 0.3)",
          }}
        >
          Calculate My BMR →
        </button>
        {result && (
          <button
            onClick={reset}
            className="px-5 py-3.5 rounded-lg font-body font-bold text-xs uppercase tracking-wide border cursor-pointer transition-colors"
            style={{
              background: "transparent",
              color: "hsl(var(--muted-foreground))",
              borderColor: "hsl(var(--border))",
            }}
          >
            Reset
          </button>
        )}
      </div>

      <AnimatePresence>
        {result && (
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 16 }}
            transition={{ duration: 0.3 }}
          >
            {/* Numbers */}
            <div
              className={`grid gap-3 mb-4 ${isMobile ? "grid-cols-1" : "grid-cols-3"}`}
            >
              {[
                {
                  label: "BMR",
                  sub: "Base metabolic rate",
                  value: `${result.bmr} kcal`,
                  color: "hsl(20 100% 50%)",
                  icon: "🔥",
                },
                {
                  label: "TDEE",
                  sub: "Daily maintenance",
                  value: `${result.tdee} kcal`,
                  color: "hsl(217 91% 53%)",
                  icon: "⚡",
                },
                {
                  label: "Daily Target",
                  sub: goalLabel,
                  value: `${result.target} kcal`,
                  color: goalColor,
                  icon: goalIcon,
                },
              ].map((s) => (
                <div
                  key={s.label}
                  className="mk2-card text-center"
                  style={{ borderTop: `3px solid ${s.color}` }}
                >
                  <div className="text-2xl mb-2">{s.icon}</div>
                  <div
                    className="font-display text-[28px] leading-none mb-1"
                    style={{ color: s.color }}
                  >
                    {s.value}
                  </div>
                  <div className="font-bold text-sm">{s.label}</div>
                  <div className="text-[10px] text-muted-foreground mt-0.5">
                    {s.sub}
                  </div>
                </div>
              ))}
            </div>

            {/* Protein */}
            <div
              className="mk2-card mb-4 flex items-center gap-4"
              style={{ borderLeft: "3px solid hsl(38 92% 44%)" }}
            >
              <span className="text-3xl">🥩</span>
              <div>
                <div className="font-bold text-sm">Protein Target</div>
                <div className="text-muted-foreground text-xs mt-0.5">
                  Based on body weight for your goal
                </div>
              </div>
              <div
                className="ml-auto font-display text-[28px]"
                style={{ color: "hsl(38 92% 44%)" }}
              >
                {result.protein}g
                <span className="text-sm text-muted-foreground font-body">
                  /day
                </span>
              </div>
            </div>

            {/* Recommendation */}
            <div
              className="mk2-card mb-5"
              style={{ borderLeft: "3px solid hsl(187 85% 40%)" }}
            >
              <div className="font-bold text-sm mb-2">💡 Recommendation</div>
              <div className="text-sm text-muted-foreground leading-relaxed">
                {result.recommendation}
              </div>
            </div>

            {/* Copy button */}
            <button
              onClick={copyToAI}
              className="w-full py-3.5 rounded-lg font-body font-bold text-sm uppercase tracking-[0.08em] border cursor-pointer transition-all duration-200 flex items-center justify-center gap-2 mb-3"
              style={{
                background: copied ? "hsl(142 72% 37% / 0.15)" : "transparent",
                color: copied ? "hsl(142 72% 37%)" : "hsl(20 100% 50%)",
                borderColor: copied ? "hsl(142 72% 37%)" : "hsl(20 100% 50%)",
              }}
            >
              {copied ? "✅ Copied!" : "📋 Copy Results to AI Nutrition Coach"}
            </button>
            <div className="text-[11px] text-muted-foreground text-center">
              Copy your results then go to{" "}
              <strong className="text-foreground">Nutrition Coach</strong> and
              paste them for a personalised meal plan
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {!result && (
        <div className="mk2-card bg-secondary/50">
          <div className="font-bold text-sm mb-2">What is BMR?</div>
          <div className="text-xs text-muted-foreground leading-relaxed">
            Your{" "}
            <strong className="text-foreground">
              Basal Metabolic Rate (BMR)
            </strong>{" "}
            is the calories your body burns at rest. Your{" "}
            <strong className="text-foreground">TDEE</strong> accounts for your
            activity level. Use these to set your daily calorie target — then
            copy the results straight to the AI Nutrition Coach for a
            personalised meal plan.
          </div>
        </div>
      )}
    </div>
  );
}
